import axios from "axios";
import Head from "next/head";
import { Fragment, useEffect, useState } from "react";
import MainPageLayout from "../components/layout/mainpagelayout/MainPageLayout";
import MainPage from "../components/mainPage/MainPage";
import getTitles from "../helpers/dataCenter";
import Spinner from "../helpers/Spinner";

export default function Home(props) {
  const content = props.content;
  // state of side navigation
  const [showSideNavDesktop, setshowSideNavDesktop] = useState(false);
  const [loading, setLoading] = useState(false);
  const [sections, setSections] = useState();

  useEffect(() => {
    fetchTitles();
  }, []);

  const fetchTitles = async () => {
    const data = await getTitles();
    setSections(data);
  };

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <Spinner />
      ) : (
        <div onClickCapture={() => setshowSideNavDesktop(false)}>
          <MainPageLayout
            content={content}
            showSideNavDesktop={showSideNavDesktop}
            setshowSideNavDesktop={setshowSideNavDesktop}
            sections={sections}
            setLoading={setLoading}
          >
            <MainPage content={content} />
          </MainPageLayout>
        </div>
      )}
    </Fragment>
  );
}
export async function getStaticProps() {
  const baseUrl =
    "https://api.nytimes.com/svc/topstories/v2/home.json?api-key=EhgvtA3WE0sRHZeL6sQ8LPFZtn2CtGFz";

  const data = await axios.get(baseUrl);

  return {
    props: {
      content: data.data,
    },
    revalidate: 60000,
  };
}
